name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: install dependencies
        run: npm ci
        working-directory: backend

  build-client:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: install dependencies
        run: npm install
        working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client
